"""Shared EHUDAction ordinals from Source/CoopRTS/CommandHUD.h."""

BUILD_BARRACKS, RECIPE_RANGED, RECIPE_SIEGE, TOGGLE_PRODUCTION, RESEARCH_REPAIRS = (
    1,
    6,
    7,
    8,
    13,
)
CONSTRUCTION = 15
ORDER_MOVE_HOLD, ORDER_ATTACK, ORDER_RETREAT = 37, 38, 39
SELECT_FORCE = 44
