"""Shared EHUDAction ordinals from Source/CoopRTS/CommandHUD.h."""

BUILD_BARRACKS, RECIPE_RANGED, RECIPE_SIEGE, TOGGLE_PRODUCTION, RESEARCH_REPAIRS = (
    1,
    6,
    7,
    8,
    13,
)
CONSTRUCTION = 15
GOAL_HOLD, GOAL_EXPAND, GOAL_ASSAULT, GOAL_FALL_BACK = 37, 38, 39, 40
