"""Destroy authored HQ guards through real force selection and minimap Attack."""

from __future__ import annotations

from harness.network import (
    ATTACK,
    NetworkRun,
    alive_units,
    building,
    force,
    minimap_world_point,
    order_matches,
    require,
    select_producer_force,
)
from harness.network_outcomes import objective_event
from harness.network_session import Session, converged
from harness.verify import ROOT, JsonObject
from x import jsonio


def guard_loss_confirmed(
    state: JsonObject, node: JsonObject, remaining: int, after: int
) -> bool:
    return state["enemyHQ"] == 900 and any(
        event["id"] == "enemy_node_lost"
        and event["sequence"] > after
        and event["position"][:2] == node["pos"]
        and event["affectedTeam"] == 5
        and event["damageTier"] == remaining
        for event in state["objectiveEvents"]
    )


def attack_guard_node(
    run: NetworkRun, s: Session, index: int, node: JsonObject, remaining: int
) -> None:
    events = run.observe("host")["objectiveEvents"]
    after = int(events[-1]["sequence"]) if events else 0
    selected = select_producer_force(run, s.peer, index)
    force_number = building(selected, index)["forceNumber"]
    attacks = {
        unit["slot"]: unit["attacks"]
        for unit in alive_units(force(selected, s.owner, index))
    }
    point = minimap_world_point(selected, node["pos"])
    run.request(s.peer, "orderClick", x=point[0], y=point[1], queue=False)
    converged(
        run,
        s.names,
        lambda st: (
            order_matches(st, index, ATTACK, node["region"])
            and building(st, index)["targetStructureId"] >= 0
            and building(st, index)["targetStructureId"] != st["enemyHQId"]
        ),
        f"Attack targets guard node {node['id']} on every peer",
    )
    converged(
        run,
        s.names,
        lambda st: any(
            unit["attacks"] > attacks[unit["slot"]]
            for unit in alive_units(force(st, s.owner, index))
        ),
        f"produced force physically reaches and fires at guard node {node['id']}",
    )
    states = objective_event(
        run, s, "enemy_node_lost", node["region"], s.owner, force_number, after
    )
    require(
        all(guard_loss_confirmed(st, node, remaining, after) for st in states.values()),
        f"guard node {node['id']} loss must replicate exact site and remaining count before HQ damage",
    )
    run.phase(
        f"real attacks destroy guard node {node['id']}; loss and remaining guards agree on every peer"
    )


def attack_guard_nodes(run: NetworkRun, s: Session, index: int) -> None:
    state = run.observe("host")
    # Boot is generated by MatchLayout without guard nodes. Authored maps
    # supply real minimap targets; an unknown/missing layout fails closed.
    if state["map"] == "/Game/Maps/Boot":
        return
    layout = jsonio.load(
        ROOT / "Build/Maps" / f"{state['map'].rsplit('/', 1)[-1]}.json"
    )
    require(
        layout["unreal_map"] == state["map"], "guard layout does not match live map"
    )
    nodes = [node for node in layout.get("failover_nodes", []) if node["team"] == 5]
    for ordinal, node in enumerate(nodes):
        attack_guard_node(run, s, index, node, len(nodes) - ordinal - 1)
