"""Land regenerates binaries from changed text sources; the hook rejects other binary commits."""

from pathlib import Path

from conftest import git
from landing_support import commit_file, git_result, install_runner, invoke
import pytest
from x.content.regeneration import SUBJECT

MAP = """[[generated]]
name = "fake"
gen = ["fake-assets"]
sources = ["Build/Content/fake.json", "Build/GenerateFake.py"]
outputs = ["Content/Fake/**"]

[[authored]]
name = "hand"
reason = "hand-made import"
paths = ["Content/Art/hand.uasset"]
"""
SCRIPT = """import json
from pathlib import Path

data = json.loads(Path("Build/Content/fake.json").read_text())
target = Path("Content/Fake/asset.uasset")
target.parent.mkdir(parents=True, exist_ok=True)
target.write_text(f"value={data['value']}\\n")
if data.get("stray"):
    Path("Docs/stray.md").write_text("stray\\n")
"""
ENTRY = 'Generator("fake-assets", "python", "GenerateFake.py", "Content/Fake/**", "Fake."),\n'


def write(repo: Path, path: str, text: str) -> None:
    target = repo / path
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(text)


@pytest.fixture
def task(repo: Path) -> Path:
    task = install_runner(repo)
    registry = repo / "Tools/x/content/registry.py"
    registry.write_text(
        registry.read_text().replace("GENERATORS = (\n", "GENERATORS = (\n    " + ENTRY)
    )
    write(repo, "Tools/x/generated.toml", MAP)
    write(repo, "Build/GenerateFake.py", SCRIPT)
    write(repo, "Build/Content/fake.json", '{"value": 0}\n')
    write(repo, "Content/Fake/asset.uasset", "value=0\n")
    write(repo, "Content/Art/hand.uasset", "hand\n")
    git(repo, "add", ".")
    git(repo, "commit", "-m", "fake generator and map")
    git(task, "rebase", "main")
    assert invoke(task, "help").returncode == 0  # installs the shared hooks
    return task


def subjects(repo: Path) -> list[str]:
    return git(repo, "log", "--format=%s", "main..HEAD").splitlines()


def forge_commit(repo: Path, path: str, text: str, subject: str) -> str:
    """Commit without hooks (plumbing), standing in for a crash or a skipped hook."""
    write(repo, path, text)
    git(repo, "add", path)
    tree = git(repo, "write-tree")
    commit = git(repo, "commit-tree", tree, "-p", "HEAD", "-m", subject)
    git(repo, "reset", "-q", "--hard", commit)
    return commit


def test_source_change_regenerates_and_commits_binaries(repo: Path, task: Path) -> None:
    commit_file(task, "Build/Content/fake.json", '{"value": 7}\n')
    result = invoke(task, "land")
    assert result.returncode == 0, result.stdout + result.stderr
    assert "regenerating fake via ./x gen fake-assets" in result.stdout
    assert (repo / "Content/Fake/asset.uasset").read_text() == "value=7\n"
    assert git(repo, "log", "--format=%s", "-2").splitlines() == [
        SUBJECT,
        "change Build/Content/fake.json",
    ]
    assert git(repo, "show", "--name-only", "--format=", "HEAD").splitlines() == [
        "Content/Fake/asset.uasset"
    ]
    assert git(task, "status", "--porcelain") == ""


def test_unchanged_outputs_make_no_regeneration_commit(repo: Path, task: Path) -> None:
    commit_file(task, "Build/GenerateFake.py", SCRIPT + "# comment\n")
    result = invoke(task, "land")
    assert result.returncode == 0, result.stdout + result.stderr
    assert "identical; no commit needed" in result.stdout
    assert SUBJECT not in git(repo, "log", "--format=%s", "-3")


def test_land_without_generated_sources_regenerates_nothing(
    repo: Path, task: Path
) -> None:
    commit_file(task, "Docs/task.md", "text only\n")
    result = invoke(task, "land")
    assert result.returncode == 0, result.stdout + result.stderr
    assert "nothing to regenerate" in result.stdout
    assert (
        git(repo, "log", "--format=%s", "-2").splitlines()[0] == "change Docs/task.md"
    )
    (record,) = (repo.parent / "runs").glob("*-land-*")
    assert not list(record.glob("regenerate-*.log"))


def test_generated_binary_without_source_is_rejected(repo: Path, task: Path) -> None:
    write(task, "Content/Fake/asset.uasset", "value=99\n")
    git(task, "add", "Content/Fake/asset.uasset")
    result = git_result(task, "commit", "-m", "hand edit")
    assert result.returncode != 0
    assert "committed only by ./x land" in result.stderr
    assert "Content/Fake/asset.uasset: generated by fake from" in result.stderr
    assert "./x land regenerates and commits the binary" in result.stderr
    assert "./x gen fake-assets" in result.stderr
    assert subjects(task) == []


def test_binary_committed_with_its_source_is_still_rejected(
    repo: Path, task: Path
) -> None:
    write(task, "Build/Content/fake.json", '{"value": 3}\n')
    write(task, "Content/Fake/asset.uasset", "value=3\n")
    git(task, "add", ".")
    result = git_result(task, "commit", "-m", "source and binary")
    assert result.returncode != 0
    assert "Content/Fake/asset.uasset" in result.stderr


def test_authored_binaries_pass_commit_and_land(repo: Path, task: Path) -> None:
    commit_file(task, "Content/Art/hand.uasset", "retouched\n")
    result = invoke(task, "land")
    assert result.returncode == 0, result.stdout + result.stderr
    assert "nothing to regenerate" in result.stdout
    assert (repo / "Content/Art/hand.uasset").read_text() == "retouched\n"


def test_unmapped_binary_is_rejected(repo: Path, task: Path) -> None:
    write(task, "Content/New/thing.umap", "new\n")
    git(task, "add", "Content/New/thing.umap")
    result = git_result(task, "commit", "-m", "new binary")
    assert result.returncode != 0
    assert "Content/New/thing.umap: unmapped binary" in result.stderr


def test_commit_cannot_reclassify_its_outputs_as_authored(
    repo: Path, task: Path
) -> None:
    write(
        task,
        "Tools/x/generated.toml",
        MAP.replace('"Content/Art/hand.uasset"', '"Content/Fake/**"'),
    )
    write(task, "Content/Fake/asset.uasset", "value=5\n")
    git(task, "add", ".")
    assert git_result(task, "commit", "-m", "reclassify").returncode != 0


def test_retry_after_failed_check_keeps_one_regeneration_commit(
    repo: Path, task: Path
) -> None:
    commit_file(task, "Build/Content/fake.json", '{"value": 4}\n')
    commit_file(task, "Docs/fail.md", "fail the selected scope\n")
    commit_file(task, "Tools/check.txt", "select tools\n")
    first = invoke(task, "land")
    assert first.returncode == 1 and "check failed" in first.stdout
    assert SUBJECT not in subjects(task)
    assert git(task, "status", "--porcelain") == ""
    git(task, "rm", "-q", "Docs/fail.md")
    git(task, "commit", "-m", "fix")
    second = invoke(task, "land")
    assert second.returncode == 0, second.stdout + second.stderr
    landed = git(repo, "log", "--format=%s", "-8").splitlines()
    assert landed.count(SUBJECT) == 1
    assert (repo / "Content/Fake/asset.uasset").read_text() == "value=4\n"


def test_generator_writing_outside_outputs_is_refused_and_undone(
    repo: Path, task: Path
) -> None:
    commit_file(task, "Build/Content/fake.json", '{"value": 1, "stray": true}\n')
    before = git(repo, "rev-parse", "HEAD")
    result = invoke(task, "land")
    assert result.returncode == 1
    assert "wrote outside their declared outputs: Docs/stray.md" in result.stdout
    assert git(task, "status", "--porcelain") == ""
    assert not (task / "Docs/stray.md").exists()
    assert git(repo, "rev-parse", "HEAD") == before


def test_generator_failure_is_refused(repo: Path, task: Path) -> None:
    commit_file(task, "Build/Content/fake.json", "not json\n")
    result = invoke(task, "land")
    assert result.returncode == 1
    assert "./x gen fake-assets failed" in result.stdout
    assert git(task, "status", "--porcelain") == ""


def test_refusal_after_regeneration_keeps_local_formatting(
    repo: Path, task: Path
) -> None:
    commit_file(task, "Build/Content/fake.json", '{"value": 6}\n')
    commit_file(task, "Tools/x/unformatted.py", "answer=1\n")
    base = git(task, "rev-parse", "HEAD")
    result = invoke(task, "land")
    assert result.returncode == 1 and "check reformatted files" in result.stdout
    assert git(task, "rev-parse", "HEAD") == base
    assert (task / "Tools/x/unformatted.py").read_text() == "answer = 1\n"
    assert (task / "Content/Fake/asset.uasset").read_text() == "value=0\n"
    assert git(task, "status", "--porcelain").split() == ["M", "Tools/x/unformatted.py"]


def test_crashed_land_leftover_is_dropped_but_lookalikes_are_kept(
    repo: Path, task: Path
) -> None:
    commit_file(task, "Docs/work.md", "work\n")
    forge_commit(task, "Docs/lookalike.md", "mine\n", SUBJECT)
    forge_commit(task, "Content/Fake/asset.uasset", "value=9\n", SUBJECT)
    result = invoke(task, "land")
    assert result.returncode == 0, result.stdout + result.stderr
    assert (repo / "Content/Fake/asset.uasset").read_text() == "value=0\n"
    assert (repo / "Docs/lookalike.md").read_text() == "mine\n"
    assert (repo / "Docs/work.md").read_text() == "work\n"


def test_branch_commit_changing_generated_output_is_refused(
    repo: Path, task: Path
) -> None:
    commit_file(task, "Docs/task.md", "text\n")
    forge_commit(task, "Content/Fake/asset.uasset", "value=8\n", "sneaky")
    before = git(repo, "rev-parse", "HEAD")
    result = invoke(task, "land")
    assert result.returncode == 1
    assert "branch commits change generated binaries" in result.stdout
    assert "Content/Fake/asset.uasset" in result.stdout
    assert git(repo, "rev-parse", "HEAD") == before


def test_generated_outputs_already_on_main_do_not_trip_land(
    repo: Path, task: Path
) -> None:
    other = repo.parent / "other"
    git(repo, "worktree", "add", "-b", "task/other", str(other))
    commit_file(other, "Build/Content/fake.json", '{"value": 2}\n')
    assert invoke(other, "land").returncode == 0
    assert (repo / "Content/Fake/asset.uasset").read_text() == "value=2\n"
    commit_file(task, "Docs/task.md", "text\n")
    result = invoke(task, "land")
    assert result.returncode == 0, result.stdout + result.stderr
    assert "nothing to regenerate" in result.stdout
    assert (repo / "Content/Fake/asset.uasset").read_text() == "value=2\n"
