"""The source-to-output map: glob rules, rejection policy and agreement with the repository."""

import ast
from pathlib import Path
import subprocess

import pytest
from x.content import generated
from x.content.registry import BY_NAME

ROOT = Path(__file__).parents[2]
MAP = generated.load(ROOT)


def tracked() -> list[str]:
    output = subprocess.check_output(["git", "-C", str(ROOT), "ls-files", "-z"])
    return [path for path in output.decode().split("\0") if path]


@pytest.mark.parametrize(
    ("pattern", "path", "expected"),
    [
        ("Content/Units/**", "Content/Units/DA_A.uasset", True),
        ("Content/Units/**", "Content/Units/Sub/DA_A.uasset", True),
        ("Content/Units/*.uasset", "Content/Units/Sub/DA_A.uasset", False),
        ("Content/**/*.uasset", "Content/DA_A.uasset", True),
        ("Content/**/*.uasset", "Content/A/B/DA_A.uasset", True),
        ("Art/Units/*.fbx", "Art/Units/SM_A.fbx", True),
        ("Art/Units/*.fbx", "Art/UnitsX/SM_A.fbx", False),
        (
            "Content/Art/Materials/MI_AZ_*.uasset",
            "Content/Art/Materials/MI_AZ_Rust.uasset",
            True,
        ),
        ("a.b", "aXb", False),
        ("a?c", "a/c", False),
    ],
)
def test_glob_is_anchored_and_directory_aware(
    pattern: str, path: str, expected: bool
) -> None:
    assert generated.matches(pattern, path) is expected


def test_every_tracked_binary_has_exactly_one_owner() -> None:
    binaries = [path for path in tracked() if generated.is_binary(path)]
    owners = {path: generated.owner(MAP, path) for path in binaries}
    assert [path for path, found in owners.items() if len(found) != 1] == []


def test_every_pattern_matches_a_tracked_file() -> None:
    files = tracked()
    stale: list[str] = []
    for entry in MAP.entries:
        for pattern in (*entry.sources, *entry.outputs):
            if not any(generated.matches(pattern, path) for path in files):
                stale.append(f"{entry.name}: {pattern}")
    for item in MAP.authored:
        stale += [
            f"{item.name}: {pattern}"
            for pattern in item.paths
            if not any(generated.matches(pattern, path) for path in files)
        ]
    assert stale == []


def test_every_entry_runs_registered_generators() -> None:
    unknown = [
        f"{entry.name}: {name}"
        for entry in MAP.entries
        for name in entry.gen
        if name not in BY_NAME
    ]
    assert unknown == []


def test_unit_stat_source_triggers_match_content_only() -> None:
    entries = generated.triggered(MAP, ["Build/Content/units.json", "Docs/Design.md"])
    assert [entry.name for entry in entries] == ["match-content"]
    assert entries[0].gen == ("generate-match-content",)


def test_triggered_keeps_map_order_and_shared_sources_trigger_all_users() -> None:
    entries = generated.triggered(MAP, ["Build/ArtMaterials.py"])
    names = [entry.name for entry in entries]
    assert names == [entry.name for entry in MAP.entries if entry.name in names]
    assert {"shared-material", "campus-zero", "availability-zone"} <= set(names)


def test_rejections_use_every_map_so_a_commit_cannot_reclassify() -> None:
    staged = generated.parse(
        '[[authored]]\nname = "x"\nreason = "r"\npaths = ["Content/Units/**"]\n'
    )
    path = "Content/Units/DA_Frontline.uasset"
    assert generated.rejections([staged], [path]) == []
    (message,) = generated.rejections([staged, MAP], [path])
    assert message.startswith(path + ": generated by match-content")


@pytest.mark.parametrize(
    "text",
    [
        '[[generated]]\nname = "a"\ngen = []\nsources = ["s"]\noutputs = ["o"]\n',
        '[[generated]]\nname = "a"\ngen = ["g"]\nsources = ["s"]\n',
        '[[generated]]\nname = "a"\ngen = ["g"]\nsources = ["s"]\noutputs = ["o"]\n'
        '[[authored]]\nname = "a"\nreason = "r"\npaths = ["p"]\n',
        '[[authored]]\nname = "a"\nreason = ""\npaths = ["p"]\n',
    ],
)
def test_malformed_map_is_rejected(text: str) -> None:
    with pytest.raises(ValueError, match=r"generated\.toml"):
        generated.parse(text)


def _assigned(script: str, name: str) -> ast.expr:
    tree = ast.parse((ROOT / "Build" / script).read_text(encoding="utf-8"))
    (value,) = (
        node.value
        for node in tree.body
        if isinstance(node, ast.Assign)
        and any(isinstance(t, ast.Name) and t.id == name for t in node.targets)
    )
    return value


def _owner_names(instances: list[str]) -> set[tuple[str, str]]:
    return {
        (name, entry.name)
        for name in instances
        for entry in generated.owner(MAP, f"Content/Art/Materials/{name}.uasset")
    }


def test_terrain_variants_are_owned_only_by_terrain_kit() -> None:
    variants = _assigned("TerrainKit.py", "VARIANTS")
    assert isinstance(variants, ast.Dict)
    names = [ast.literal_eval(key) for key in variants.keys if key is not None]
    assert len(names) >= 3
    assert _owner_names(names) == {(name, "terrain-kit") for name in names}


def test_shared_scope_instances_are_owned_only_by_shared_material() -> None:
    slots = ast.literal_eval(_assigned("BuildSharedMaterial.py", "SLOTS_OF_SCOPE"))
    factions = ast.literal_eval(
        _assigned("BuildSharedMaterial.py", "FACTIONS_OF_SCOPE")
    )
    names = [
        f"MI_SC2_{faction}_{slot}_{scope}"
        for scope, scope_slots in slots.items()
        for faction in (
            *factions[scope],
            *(("Construction",) if scope == "Bld" else ()),
        )
        for slot in scope_slots
    ]
    assert _owner_names(names) == {(name, "shared-material") for name in names}
