[/Script/EngineSettings.GeneralProjectSettings]
ProjectID=36F6D9AB44C44F9EB8F550CE616BD734
ProjectName=CoopRTS
ProjectVersion=0.0.1
Description=Cooperative army-command RTS roguelite.

[/Script/UnrealEd.ProjectPackagingSettings]
BuildConfiguration=PPBC_Development
FullRebuild=False
ForDistribution=False
bUsePakFile=True
bUseIoStore=True
+MapsToCook=(FilePath="/Game/Maps/Boot")
+MapsToCook=(FilePath="/Game/Maps/CampusZero")
+MapsToCook=(FilePath="/Game/Maps/AvailabilityZone")
+MapsToCook=(FilePath="/Game/Maps/AvailabilityZoneV2")
+MapsToCook=(FilePath="/Game/Maps/Menu")
+DirectoriesToAlwaysCook=(Path="/Game/Audio")
+DirectoriesToAlwaysCook=(Path="/Game/Materials/Overlay")

[/Script/Engine.AssetManagerSettings]
; GameFeaturesEditor requires a non-default AlwaysCook rule when AllToolsets enables GameFeatures.
+PrimaryAssetTypesToScan=(PrimaryAssetType="GameFeatureData",AssetBaseClass=/Script/GameFeatures.GameFeatureData,bHasBlueprintClasses=False,bIsEditorOnly=False,Directories=,SpecificAssets=,Rules=(Priority=-1,ChunkId=-1,bApplyRecursively=True,CookRule=AlwaysCook))
