// Generated by Build/GenerateGameplayConstants.py from Build/Content/constants.json.
// Change the constant there and run ./x gen generate-gameplay-constants; do not edit this file.
#pragma once

#include "CoreMinimal.h"

namespace GameplayConstants
{
constexpr int32 StartingResources = 600;
constexpr int32 BaselineIncome = 2;
constexpr int32 NormalDepositRate = 4;
constexpr int32 RichDepositRate = 6;
constexpr int32 NormalDepositAmount = 2400;
constexpr int32 RichDepositAmount = 3000;
constexpr float CaptureRadius = 430.f;
constexpr float HostileHqClearance = 1000.f;
}
