// Generated by Build/GenerateGameplayConstants.py from Build/Content/constants.json.
// Change the constant there and run ./x gen generate-gameplay-constants; do not edit this file.
#pragma once

#include "CoreMinimal.h"

namespace GameplayConstants
{
constexpr int32 StartingResources = 600;
constexpr int32 HumanBaselineIncome = 2;
constexpr int32 JevBaselineIncome = 2;
constexpr int32 RewardRegionDataRate = 1;
constexpr int32 StructureKillData = 60;
constexpr int32 NormalDepositRate = 4;
constexpr int32 RichDepositRate = 6;
constexpr int32 NormalDepositAmount = 1200;
constexpr int32 RichDepositAmount = 1500;
constexpr float CaptureRadius = 430.f;
constexpr float HostileHqClearance = 1000.f;
constexpr float PlacementZTolerance = 110.f;
constexpr float PlacementBoxCentreZ = 65.f;
constexpr float PlacementBoxHalfZ = 55.f;
constexpr float FormationSpacing = 110.f;
}
