"""Source-to-output map for generated binary assets (Tools/x/generated.toml).

Pure standard library: the commit hook imports this module too.
"""

from dataclasses import dataclass
from functools import cache
from pathlib import Path
import re
import tomllib

MAP_PATH = "Tools/x/generated.toml"
BINARY_SUFFIXES = (".uasset", ".umap")


@dataclass(frozen=True)
class Entry:
    name: str
    gen: tuple[str, ...]
    sources: tuple[str, ...]
    outputs: tuple[str, ...]


@dataclass(frozen=True)
class Authored:
    name: str
    reason: str
    paths: tuple[str, ...]


@dataclass(frozen=True)
class GeneratedMap:
    entries: tuple[Entry, ...]
    authored: tuple[Authored, ...]


@cache
def _regex(pattern: str) -> re.Pattern[str]:
    parts: list[str] = []
    index = 0
    while index < len(pattern):
        if pattern.startswith("**/", index):
            parts.append("(?:.*/)?")
            index += 3
        elif pattern.startswith("**", index):
            parts.append(".*")
            index += 2
        elif pattern[index] == "*":
            parts.append("[^/]*")
            index += 1
        elif pattern[index] == "?":
            parts.append("[^/]")
            index += 1
        else:
            parts.append(re.escape(pattern[index]))
            index += 1
    return re.compile("".join(parts))


def matches(pattern: str, path: str) -> bool:
    """Anchored glob: `*` and `?` stay in a directory, `**` crosses directories."""
    return _regex(pattern).fullmatch(path) is not None


def matches_any(patterns: tuple[str, ...], path: str) -> bool:
    return any(matches(pattern, path) for pattern in patterns)


def _strings(table: dict[str, object], key: str, where: str) -> tuple[str, ...]:
    value = table.get(key)
    if (
        not isinstance(value, list)
        or not value
        or not all(isinstance(item, str) for item in value)
    ):
        raise ValueError(f"{MAP_PATH}: {where} needs a non-empty string list {key!r}")
    return tuple(value)


def parse(text: str) -> GeneratedMap:
    data = tomllib.loads(text)
    entries: list[Entry] = []
    authored: list[Authored] = []
    names: set[str] = set()
    for table in data.get("generated", []):
        name = table.get("name")
        if not isinstance(name, str) or name in names:
            raise ValueError(f"{MAP_PATH}: missing or duplicate entry name {name!r}")
        names.add(name)
        where = f"entry {name}"
        entries.append(
            Entry(
                name,
                _strings(table, "gen", where),
                _strings(table, "sources", where),
                _strings(table, "outputs", where),
            )
        )
    for table in data.get("authored", []):
        name = table.get("name")
        reason = table.get("reason")
        if not isinstance(name, str) or name in names:
            raise ValueError(f"{MAP_PATH}: missing or duplicate entry name {name!r}")
        if not isinstance(reason, str) or not reason:
            raise ValueError(f"{MAP_PATH}: authored {name} needs a reason")
        names.add(name)
        authored.append(Authored(name, reason, _strings(table, "paths", name)))
    return GeneratedMap(tuple(entries), tuple(authored))


def load(repo: Path) -> GeneratedMap:
    return parse((repo / MAP_PATH).read_text(encoding="utf-8"))


def triggered(mapping: GeneratedMap, changed: list[str]) -> list[Entry]:
    """Entries whose sources changed, in map order."""
    return [
        entry
        for entry in mapping.entries
        if any(matches_any(entry.sources, path) for path in changed)
    ]


def owner(mapping: GeneratedMap, path: str) -> list[Entry | Authored]:
    """Every entry claiming `path` as an output or authored binary."""
    found: list[Entry | Authored] = [
        entry for entry in mapping.entries if matches_any(entry.outputs, path)
    ]
    found.extend(item for item in mapping.authored if matches_any(item.paths, path))
    return found


def is_binary(path: str) -> bool:
    return path.endswith(BINARY_SUFFIXES)


def rejections(maps: list[GeneratedMap], staged: list[str]) -> list[str]:
    """One message per staged path that only `./x land` may commit.

    A path is generated when any supplied map says so, so a commit cannot
    reclassify its own outputs as authored.
    """
    messages: list[str] = []
    for path in staged:
        generators = [
            entry
            for mapping in maps
            for entry in mapping.entries
            if matches_any(entry.outputs, path)
        ]
        if generators:
            entry = generators[0]
            sources = ", ".join(entry.sources)
            gens = " ".join(f"./x gen {name};" for name in entry.gen)
            messages.append(
                f"{path}: generated by {entry.name} from {sources}. Change a text "
                f"source instead; ./x land regenerates and commits the binary "
                f"(preview locally with {gens} do not commit its output)."
            )
        elif is_binary(path) and not any(owner(mapping, path) for mapping in maps):
            messages.append(
                f"{path}: unmapped binary. Add it to {MAP_PATH} as generated "
                "(with its sources) or authored (with a reason)."
            )
    return messages
